# Generated by Django 5.2.7 on 2025-10-22 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0003_remove_resume_education_history_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobhistory',
            name='end_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='jobhistory',
            name='start_date',
            field=models.DateField(),
        ),
    ]
